#!/usr/bin/env python

try:
  # attempt to use the installed python package
  import ac2imp
except:
  # attempt to run the package from the source directory
  import sys
  sys.path.insert (0,'src')
  import ac2imp
  

if __name__ == '__main__':
    a=ac2imp.ac2imp()
    a.MainLoop()
